//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D42_POC_Demo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D42_POC_Demo.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///DOQL for detailed data of Devices related to Discovery Scores and Job Scores.
        ///*/
        ///select 
        ///ds.discoveryscores_pk &quot;Discovery Score ID&quot;,
        ///vsd.vserverdiscovery_pk &quot;Job ID&quot;,
        ///vsd.job_name &quot;Job Name&quot;,
        ///vsd.platform &quot;Platform&quot;,
        ///ds.port &quot;TCP Port&quot;,
        ///ds.discovery_server &quot;Discovery Target&quot;,
        ///ds.username &quot;Username&quot;,
        ///CASE
        ///  WHEN ds.port_check = &apos;t&apos;
        ///  THEN
        ///  &apos;PASS&apos;
        ///  ELSE
        ///  &apos;FAIL&apos;
        ///END &quot;Port Check&quot;,
        ///CASE
        ///  WHEN ds.authorization = &apos;t&apos;
        ///  THEN
        ///  &apos;PASS&apos;
        ///  ELSE
        ///  &apos;FAIL&apos;
        ///END &quot;Auth Check&quot;,
        ///CASE
        ///  WHEN ds.is_sudo_failed = &apos;t&apos;
        ///  THE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string advanced_discovery_scores_RO {
            get {
                return ResourceManager.GetString("advanced_discovery_scores_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     select
        ///        d.last_edited &quot;Last_Discovered&quot;,
        ///        d.name &quot;Device_Name&quot;,
        ///        d.in_service &quot;In Service&quot;,
        ///        d.service_level &quot;Service_Level&quot;,
        ///        d.type &quot;Device_Type&quot;,
        ///        d.sub_type &quot;Device Subtype&quot;,
        ///        d.virtual_subtype &quot;Virtual_Subtype&quot;,
        ///        d.serial_no &quot;Device_Serial&quot;,
        ///        d.virtual_host &quot;Virtual Host&quot;,
        ///        d.network_device &quot;Network Device&quot;,
        ///        d.os_arch &quot;OS_Arch&quot;,
        ///        d.cpucount &quot;CPU Sockets&quot;,
        ///        d.cpucore &quot;Cores Per CPU&quot;,
        ///        d.cpupower &quot;CPU S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string all_devices_RO {
            get {
                return ResourceManager.GetString("all_devices_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///DOQL for App Comp&apos;s with related software in use details.
        ///*/
        ///select
        ///ac.name &quot;App Comp&quot;,
        ///d.name &quot;Device&quot;,
        ///ip.ip_address &quot;Device IP&quot;,
        ///s.name &quot;Software Name&quot;,
        ///si.alias_name &quot;Software Alias&quot;,
        ///si.version &quot;Version&quot;
        ///from view_appcomp_v1 ac
        ///left join view_device_v1 d on d.device_pk = ac.device_fk
        ///left join view_ipaddress_v1 ip on ip.device_fk = d.device_pk
        ///left join view_softwareinuse_v1 si on si.appcomp_fk = ac.appcomp_pk
        ///left join view_software_v1 s on s.software_pk = si.software_fk.
        /// </summary>
        public static string app_comp_and_software_RO {
            get {
                return ResourceManager.GetString("app_comp_and_software_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Built to be a concise report of application components with connections.
        ///This leverages services that have been discovered with an App Comp, and joins their clients as the &quot;dependents&quot;.
        ///*/
        ///select distinct
        ///sac.name &quot;App Comp&quot;,
        ///d.name &quot;Device&quot;,
        ///s.name &quot;Software Name&quot;,
        ///siu.alias_name &quot;Software Alias&quot;,
        ///siu.version &quot;Version&quot;,
        ///sc.port &quot;Port&quot;,
        ///concat(cd.name, &apos;|&apos;, sc.client_ip, &apos;|&apos;, sc.client_process_display_name) &quot;Dependents&quot;
        ///from view_serviceinstance_v2 si
        ///left join view_servicelistenerport_v2 lp on si.servic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string app_comps_with_service_communication_RO {
            get {
                return ResourceManager.GetString("app_comps_with_service_communication_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Include connections up to 60 days*/
        ///select * from view_affinity_dependency_data_v1
        ///where family(listener_ip) &lt;&gt; 6 and listener_ip &lt;&gt; &apos;::1&apos; and listener_ip &lt;&gt; &apos;127.0.0.1&apos; and date_part(&apos;day&apos;, now() :: timestamp - client_connection_last_found :: timestamp) &lt;= 60;.
        /// </summary>
        public static string connections_in_past_60_days_RO {
            get {
                return ResourceManager.GetString("connections_in_past_60_days_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Include connections up to 90 days*/
        ///select * from view_affinity_dependency_data_v1
        ///where family(listener_ip) &lt;&gt; 6 and listener_ip &lt;&gt; &apos;::1&apos; and listener_ip &lt;&gt; &apos;127.0.0.1&apos; and date_part(&apos;day&apos;, now() :: timestamp - client_connection_last_found :: timestamp) &lt;= 90;.
        /// </summary>
        public static string connections_in_past_90_days_RO {
            get {
                return ResourceManager.GetString("connections_in_past_90_days_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Will give a count of all detailed discovery data to help identify hosts with or without detailed child objects.
        ///*/
        /// Select dh.*,
        ///     lower(deval.alias_name) &quot;Alias/FQDN&quot;
        ///     from(
        ///      Select
        ///       d.device_pk &quot;Device_ID&quot;,
        ///       lower(split_part(d.name,&apos;.&apos;,1)) &quot;Device Name (SN)&quot;,
        ///       lower(d.name) &quot;Device Name&quot;,
        ///       d.os_name &quot;Operating System&quot;,
        ///      (select count(*) from view_softwaredetails_v1 sd where sd.device_fk = d.device_pk) &quot;Software Discovered&quot;,
        ///      (select count(*) from view_servi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string count_for_detailed_discovery_data_RO {
            get {
                return ResourceManager.GetString("count_for_detailed_discovery_data_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* getting all view_deviceaffinity_v2 records for specific Affinity Group chart 
        ///    2/28/2020
        ///      Data records should support default Affinity Group Chart 
        ///      Note: Will need to add &amp;affinity_group_pk=&lt;affinity group pk or id&gt; to the Saved DOQL URL.
        ///*/
        ///WITH RECURSIVE 
        ///  impact AS ( -- impact report
        ///  SELECT da1.*
        ///  FROM view_deviceaffinity_v2 AS da1, src
        ///  WHERE da1.dependency_device_fk = src.primary_device_fk
        ///        AND da1.effective_from &lt;= src.effective_on
        ///        AND (da1.effective_to IS NULL OR  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DevicesByAffinityGroup_RO {
            get {
                return ResourceManager.GetString("DevicesByAffinityGroup_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///DOQL for Discovery Scores and Job Scores.
        ///*/
        ///select 
        ///ds.updated &quot;Timestamp&quot;,
        ///ds.discovery_type &quot;Discovery Type&quot;,
        ///ds.sub_type &quot;Discovery Subtype&quot;,
        ///js.vserverdiscovery_fk &quot;Job ID&quot;,
        ///vs.job_name &quot;Job Name&quot;,
        ///ds.current_mode &quot;Mode&quot;,
        ///ds.status &quot;Status&quot;,
        ///ds.discovery_server &quot;Target&quot;,
        ///ds.port &quot;Target Port&quot;,
        ///ds.devicename &quot;Device Name&quot;,
        ///ds.supported_os &quot;Supported OS&quot;,
        ///ds.device_added &quot;Device Added?&quot;,
        ///ds.port_check &quot;Port Check&quot;,
        ///ds.username &quot;Username&quot;,
        ///ds.authorization &quot;Authorization&quot;,
        ///js.is_local_rc &quot;Local RC&quot;,
        ///rc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Discovery_Scores_RO {
            get {
                return ResourceManager.GetString("Discovery_Scores_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Ignore hidden services*/select * from view_affinity_dependency_data_v1
        ///where family(listener_ip) &lt;&gt; 6 and listener_ip &lt;&gt; &apos;::1&apos; and listener_ip &lt;&gt; &apos;127.0.0.1&apos; and listener_service_topology_status &lt;&gt; 3 and date_part(&apos;day&apos;, now() :: timestamp - client_connection_last_found :: timestamp) &lt;= 30;.
        /// </summary>
        public static string ignore_hidden_services_RO {
            get {
                return ResourceManager.GetString("ignore_hidden_services_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Get report to Support Impact List */
        ////* Inline view of  Target service and Device data  - Filters down to just the records needed   
        ///        Change xxxxx or xxxxy to the device id of the focused host before running          */
        ///With 
        ///    src as (
        ///       Select Distinct
        ///        dev.device_pk,
        ///		dev.name
        ///       From view_device_v1 as dev
        ///         Where dev.device_pk IN (&apos;365&apos;) /* specify device pk - Can put as many entries as long as each one is put in single quotes and separated by a comma  */
        ///    ),	 
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Impact_List_enh_RO {
            get {
                return ResourceManager.GetString("Impact_List_enh_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Include IPV6*/
        ///select * from view_affinity_dependency_data_v1
        ///where listener_ip &lt;&gt; &apos;::1&apos; and listener_ip &lt;&gt; &apos;127.0.0.1&apos; and date_part(&apos;day&apos;, now() :: timestamp - client_connection_last_found :: timestamp) &lt;= 30;.
        /// </summary>
        public static string include_ipv6_connections_RO {
            get {
                return ResourceManager.GetString("include_ipv6_connections_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Affinity Group query to remove any devices with a client OS.
        ///*/
        ///select * from view_affinity_dependency_data_v1
        ///where
        ///listener_os not like &apos;%Windows 10%&apos; and listener_os not like &apos;%Windows 7%&apos; and listener_os not like &apos;%Windows 8%&apos; and listener_os not like &apos;%Windows XP%&apos; and
        ///client_os not like &apos;%Windows 10%&apos; and client_os not like &apos;%Windows 7%&apos; and client_os not like &apos;%Windows 8%&apos; and client_os not like &apos;%Windows XP%&apos; and
        ///family(listener_ip) &lt;&gt; 6 and listener_ip &lt;&gt; &apos;::1&apos; and listener_ip &lt;&gt; &apos;127.0.0.1&apos; and [rest of string was truncated]&quot;;.
        /// </summary>
        public static string no_client_os_devices_RO {
            get {
                return ResourceManager.GetString("no_client_os_devices_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///For RU data and metrics.
        ///*/
        ///select 
        ///    r.last_updated &quot;RU Data Last Updated&quot;,
        ///    d.name &quot;Device Name&quot;,
        ///    d.monitoring_enabled &quot;Monitoring Enabled&quot;,
        ///    r.rudata_pk &quot;Resource ID&quot;,
        ///    r.value &quot;Resource Value&quot;,
        ///    r.sensor_type &quot;Resource Type&quot;,
        ///    r.sensor &quot;Resource&quot;,
        ///    r.measure_type &quot;Measurement Type&quot;,
        ///    r.metric &quot;Measurement Metric&quot;,
        ///    r.timeperiod_id &quot;Time Period ID&quot;,
        ///    r.timeperiod &quot;Time Period&quot;,
        ///    rc.name &quot;Remote Collector Name&quot;,
        ///    rc.ip &quot;Remote Collector IP&quot;
        ///    from view_device_v1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string resource_utilization_RO {
            get {
                return ResourceManager.GetString("resource_utilization_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Query for all discovered connections to service instances.
        ///*/
        ///select
        ///ld.name &quot;Listening Device&quot;,
        ///ag.name &quot;Affinity Group&quot;,
        ///sc.listener_ip &quot;Listening IP&quot;,
        ///lp.port &quot;Listening Port&quot;,
        ///s.displayname &quot;Listening Service&quot;,
        ///sc.port &quot;Port Communication&quot;,
        ///sc.protocol &quot;Protocol&quot;,
        ///cd.name &quot;Client Device&quot;,
        ///sc.client_ip &quot;Client IP&quot;,
        ///sc.port &quot;Client Port Communication&quot;,
        ///sc.client_process_display_name &quot;Process Display Name&quot;,
        ///sc.client_process_name &quot;Process Name&quot;,
        ///sc.last_detected &quot;Communication Last Detected&quot;,
        ///sc.netstat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string service_communication_RO {
            get {
                return ResourceManager.GetString("service_communication_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Device mount storage information, but total&apos;d for all mounts instead of a row for each mount.
        ///*/
        ///select
        ///    a.last_edited Last_Update,
        ///    a.device_pk Device_ID,
        ///    a.name Device_name,
        ///    a.type Hardware_Type,
        ///    a.virtual_subtype Virtual_Subtype,
        ///    a.os_name OS_Name,
        ///    a.os_version OS_Version_No,
        ///    sum(c.capacity) Volume_Capacity_in_MB,
        ///    sum(c.free_capacity) Free_Space_in_MB,
        ///    sum(c.capacity - c.free_capacity) Used_Space_in_MB
        ///from
        ///    view_device_v1 a
        ///    left join view_mountpoint_v1 c o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string storage_totals_RO {
            get {
                return ResourceManager.GetString("storage_totals_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Listening devices with tags only*/select add.* from view_affinity_dependency_data_v1 add
        ///join view_device_v1 ld  on ld.device_pk = add.listener_id
        ///where family(listener_ip) &lt;&gt; 6 and listener_ip &lt;&gt; &apos;::1&apos; and listener_ip &lt;&gt; &apos;127.0.0.1&apos; and ld.tags is not null and date_part(&apos;day&apos;, now() :: timestamp - client_connection_last_found :: timestamp) &lt;= 30;.
        /// </summary>
        public static string tagged_devices_only_RO {
            get {
                return ResourceManager.GetString("tagged_devices_only_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///2019-10-25 Servers Activity and Utilization
        ///Returns discovery, RU, and service connection information to give a sense of when this device
        ///was last discovered or how it has been used. Includes fields like last attempted/successful discovery,
        ///last service comms and software install, last login, general device details and RU data. 
        ///Useful in identifying underutilized or zombie servers.
        ///*/
        ///
        ///
        ///select
        ///	ds.updated &quot;Last Attempted Discovery&quot;,
        ///	(select max(scl.last_detected) from view_servicecommunication_v2 scl w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string unused_servers_RO {
            get {
                return ResourceManager.GetString("unused_servers_RO", resourceCulture);
            }
        }
    }
}
